# 사이트 기본 설정
title: 프롬프트 엔지니어링 라이브러리
description: AI 프롬프트 엔지니어링을 위한 저장소
baseurl: "/prompt-engineering-library"
url: "https://사용자명.github.io"

# 빌드 설정
markdown: kramdown
permalink: /:categories/:title/

# 컬렉션 설정
collections:
  prompts:
    output: true
    permalink: /prompts/:name/

# 기본 프론트매터 설정
defaults:
  - scope:
      path: ""
      type: "prompts"
    values:
      layout: "prompt"

# 검색 설정
search: true

# 페이지네이션
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

paginate: 10
paginate_path: "/page:num/"

# 제외 파일
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor